version: '3.8'

services:
  publisher:
    build:
      context: Task340.Publisher
    environment:
      - KafkaConnectionString=kafka:9092
      - PostgresConnection=Host=postgres;Port=5432;Database=distcomp;Username=postgres;Password=postgres
    depends_on:
      - postgres
      - kafka

  discussion:
    build:
      context: Task340.Discussion
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  cassandra:
    image: cassandra
    container_name: my-cassandra-container
    ports:
      - "9042:9042"
    command: >
      sh -c "echo 'Executing additional setup commands...'; 
      cqlsh -e 'CREATE KEYSPACE IF NOT EXISTS distcomp WITH replication = {''class'':''SimpleStrategy'', ''replication_factor'':1};'
      cqlsh -e 'CREATE TABLE IF NOT EXISTS distcomp.tbl_Note (id bigint, news_id bigint, content text, PRIMARY KEY (id));'"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  postgres:
    image: postgres
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=distcomp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: my-zookeeper-container
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    container_name: my-kafka-container
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper