version: '3.4'

services:
  publisher:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=24110
    ports:
      - "24110"

  discussion:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=24130
    ports:
      - "24130"
