version: '3.8'

services:
  cassandra:
    image: cassandra
    container_name: my-cassandra-container
    ports:
      - "9042:9042"
    command: >
      sh -c "echo 'Executing additional setup commands...'; 
      cqlsh -e 'CREATE KEYSPACE IF NOT EXISTS distcomp WITH replication = {''class'':''SimpleStrategy'', ''replication_factor'':1};'
      cqlsh -e 'CREATE TABLE IF NOT EXISTS distcomp.tbl_Note (id bigint, news_id bigint, content text, PRIMARY KEY (id));'"
    volumes:
      - ./data:/var/lib/cassandra